# travis-ci config for the pydon project
language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade pip
- pip install .[dev]
before_script:
- flake8 pydon
- flake8 tests
script: py.test tests
